# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import inventarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50)),
                ('imagenProducto', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=inventarios.models.upload_location, width_field='width_field')),
                ('cantidadProducto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precioCompraProducto', models.IntegerField(blank=True, null=True)),
                ('precioVentaProducto', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
