# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20170521_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioCompraProducto',
            new_name='precioCostoProducto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='cantidadProducto',
            new_name='stockProducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagenProducto',
        ),
    ]
